const b4a = require('b4a')
const test = require('brittle')
const { write, read, storage, teardown } = require('./helpers')

test('multiple files', async function (t) {
  t.teardown(teardown())
  const cool = storage('cool.txt')
  const and = storage('and.txt')
  const good = storage('good.txt')
  await write(cool, 100, b4a.from('GREETINGS', 'utf-8'))
  const fstbuf = await read(cool, 100, 9)
  t.is(b4a.toString(fstbuf, 'utf-8'), 'GREETINGS')
  const sndbuf = await read(cool, 104, 3)
  t.is(b4a.toString(sndbuf, 'utf-8'), 'TIN')
  await write(and, 106, b4a.from('ORANG', 'utf-8'))
  const thdbuf = await read(and, 107, 3)
  t.is(b4a.toString(thdbuf, 'utf-8'), 'RAN')
  await write(good, 90, b4a.from('DO YOU EVER JUST... TEAPOT', 'utf-8'))
  const fthbuf = await read(good, 110, 6)
  t.is(b4a.toString(fthbuf, 'utf-8'), 'TEAPOT')
  const ffthbuf = await read(good, 86, 10)
  t.is(b4a.toString(ffthbuf, 'utf-8'), '\x00\x00\x00\x00DO YOU')
  await t.exception(() => read(good, 110, 10))
})
